<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "owlcarousel"
 *
 * Auto generated by Extension Builder 2015-02-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Owl Carousel',
	'description' => 'Inserts the Owl Carousel',
	'category' => 'plugin',
	'author' => 'Raphael Zschorsch',
	'author_email' => 'rafu1987@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.3.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
			'vhs' => ''
		),
		'conflicts' => array(
			'owl_slider' => '',
		),
		'suggests' => array(
		),
	),
);